### ISSUE TITLE
3hrs after changing the IP, dnsupdate still did not update

### ISSUE THREAD

**Issue by bjo81** [lopsided98/dnsupdate#2]
At 10.45 CEST my IPv4 and IPv6 changed, but dnsupdate did not recognize it. It only did an update after restarting it.

```
dns_services:
    - type: NSUpdate
      args:
          hostname: myhost.nsupdate.info
          secret_key: abcdef
```
