### ISSUE TITLE
disable ipv6 for FreeDNS?

### ISSUE THREAD

**Issue by ph818** [lopsided98/dnsupdate#6]
I am using the FreeDNS service with ipv4. I don't have an ipv6 IP address.

I have tried a few different things in the YAML file to try and tell dnsupdate not to try to update ipv6, but every time it tries to update it and gets this error:

Error: HTTPSConnectionPool(host='ipv6.icanhazip.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x75d4a0d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

**Comment by ph818** [comment]
Nevermind, I figured it out from your "overrides" examples. I had to add an `address_provider:` section within the FreeDNS section, as below: 

```
# Uses a web service to get IPs if a provider isn't explicitly configured

# List of services (required)
dns_services:
#     Class name for the service
    - type: FreeDNS
#     Added to try and disable ipv6
      address_provider:
          ipv6: None
#     Arguments passed to the service constructor
      args:
          ipv4_key: # Redacted
```
